import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

type typeLocal = Array<{ path: string; weight?: string; style?: string }>;

const proxima = localFont({
  src: [
    {
      path: "",
    },
  ],
  variable: "--proxima",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={proxima.className}>{children}</body>
    </html>
  );
}
